### ISSUE TITLE
What is the latest changelog 2.0.1 (1.18.2) Fabric?

### ISSUE THREAD

**Issue by ardissaps** [SolidBlock-cn/reasonable-sorting#10]

**Comment by SolidBlock-cn** [comment]
Just fixed some minor issues. And the Forge and Quilt version also relies on Cloth Config now.

**Comment by ardissaps** [comment]
I see, thanks! I found some problem and posted Issue https://github.com/SolidBlock-cn/reasonable-sorting/issues/11
