### ISSUE TITLE
Unable to Load World

### ISSUE THREAD

**Issue by ardissaps** [SolidBlock-cn/reasonable-sorting#11]
It gave me spam log and crashed.
![image](https://user-images.githubusercontent.com/82106625/180723176-35eab8ef-5fb5-4442-b655-89824bbcbb65.png)
I also tried deleting both Extended Shape and Reasonable Sorting config but still crashed, Full Log from twice attempt to launch :
https://paste.atlauncher.com/view/cca523a5-46ec-4038-a237-268ec5fb79c4

**Comment by SolidBlock-cn** [comment]
It seems that a dead loop happens. I'm not sure of the reason. You may turn off "Enable Sorting" in the mod config as a temporary solution. I'll look into it.

**Comment by ardissaps** [comment]
I downgraded to previous 2.0.0 reasonable sorting version but with latest extshape 1.6 and it does not crash as temporary solution

**Comment by SolidBlock-cn** [comment]
Is this one ok
https://github.com/SolidBlock-cn/reasonable-sorting/releases/tag/v2.0.2

**Comment by ardissaps** [comment]
> Is this one ok https://github.com/SolidBlock-cn/reasonable-sorting/releases/tag/v2.0.2

Yes, it works, should I use that instead?

**Comment by SolidBlock-cn** [comment]
Yes.

**Comment by ardissaps** [comment]
Thank you very much!
