### ISSUE TITLE
[IDEA] Custom Transfer Rule accept Tags

### ISSUE THREAD

**Issue by ardissaps** [SolidBlock-cn/reasonable-sorting#12]
As example we want to transfer all #c:foods to food, tab so we would not need to type each item individually.
![image](https://user-images.githubusercontent.com/82106625/180755950-3ce21e10-f8a7-479a-837e-55902621677c.png)
![image](https://user-images.githubusercontent.com/82106625/180756319-89117e3c-e947-4829-b2e4-b0756048508c.png)

Also ability to hide empty tabs that are all item transfered, it is to minimizing the number of mod tabs that only contain tiny number of items on them. Like certain mods add only 4 items but they made tab for it, we can fix it by transfer all of those 4 items to vanilla tab then hide their tabs for efficient tabs manager.

**Comment by SolidBlock-cn** [comment]
It will be supported since next version. Thanks for the advice.

**Comment by SolidBlock-cn** [comment]
The feature is added in the new version.
