### ISSUE TITLE
[Forge] Causes client item ID misalignment when used as a client-side mod on modded server

### ISSUE THREAD

**Issue by nicholasgrose** [SolidBlock-cn/reasonable-sorting#13]
Using Reasonable sorting as a client side mod will cause blocks in the world and items to show up as different blocks and items from what they actually are on the server. This could be fixed by either checking that Reasonable Sorting exists on both the client and the server or by modifying the creative menu exclusively, without modifying the registry.

**Comment by erengeez** [comment]
the same issue appers on quilt (i assume that on fabric as well)

**Comment by SolidBlock-cn** [comment]
It will be solved since the next version.

**Comment by SolidBlock-cn** [comment]
Fixed. In this new version, only the creative inventory is modified by default.
