### ISSUE TITLE
[Question] Not an issue, but how to config the mod

### ISSUE THREAD

**Issue by Nekkok** [SolidBlock-cn/reasonable-sorting#14]
Hello! I'm using your mod on Forge 1.18.2 along JEI. I'm trying to understand what I'm doing wrong, so to breifly summarize, I'm leaving my config .json file, hoping you'll help me.

The thing is I'm just trying to change the order of the ingredient list showing on JEI making random changes, with the intention to _completely_ change everything. In the example provided I tried to load grass and fern items after cobweb, and that group before the stone block. But it didn't do anything, even so closing and loading the game. I suppose there's nothing wrong with the mod, but me not understanding how to change the configs. I'll also leave some screenshots to show you better the results.

Thank you beforehand. :)

Config: [reasonable-sorting.json](https://gist.github.com/Nekkok/5b13749896eded464c311d1d26ed31f7)
Screenshots:
![javaw_TU4O59CsdP](https://user-images.githubusercontent.com/28939799/196013708-f05e307f-063a-438c-b200-7a292c3ee94f.png)
![javaw_WAwtvmEEb6](https://user-images.githubusercontent.com/28939799/196013709-598a29e2-9fff-4ee2-9bbf-b831cc48b699.png)

**Comment by Nekkok** [comment]
So I get it to work, but I found that this can't handle modded items unfortunately. Is this a bug?

**Comment by Nekkok** [comment]
Finally I got it to sort things, but unfortunately it doesn't work with modded items. I'm sharing my new config with you, to spot the possible error.

[reasonable-sorting.json](https://gist.github.com/Nekkok/7055fb4c64377ed8e48602f61488a27a)

**Comment by SolidBlock-cn** [comment]
The issue of sorting of modded items may be solve since next version.

**Comment by SolidBlock-cn** [comment]
Fixed.
