### ISSUE TITLE
[Forge 1.18.2] Configuration loads before all items are registered, causing some modded items to only get sorted after reloading config

### ISSUE THREAD

**Issue by Pipsqueak737** [SolidBlock-cn/reasonable-sorting#18]
I'm using this mod to sort all of the creative inventory, so I make long lists of items/blocks that get sorted in the order I write them in. Some mod's items don't get sorted immediately though, and only go to the correct position after I update the config file (using an in-game config mod), which is a bit annoying as I am trying to make the menu as organized as possible. After a game restart they get reset back to their original position. Here are a couple of screenshots to demonstrate.

Before reload:
![before](https://user-images.githubusercontent.com/81382689/198194673-e985c48f-7e17-4c4b-866c-18ab110fc91f.png)

After reload:
![after](https://user-images.githubusercontent.com/81382689/198194706-3dd38c74-a436-4221-bf6e-cc875a8be235.png)

This may somehow be related to issue #8 even though that was fixed.

**Comment by unit-a-user** [comment]
I currently have similar problem in my port for 22w42a, when transfering items.

**Comment by Pipsqueak737** [comment]
I have just noticed that it looks like the problem is caused by the configuration loading too early before all items are registered, as seen in "latest.log":
![unidentified id](https://user-images.githubusercontent.com/81382689/199091795-459e9998-eb3a-4a09-87b7-2dbfff336a73.png)
This does not occur after the configuration file is reloaded.

**Comment by SolidBlock-cn** [comment]
It should be fixed since version 2.1.0. If it continues, please reopen this issue.
