### ISSUE TITLE
1.15游戏会崩端

### ISSUE THREAD

**Issue by SunnySlopes** [SolidBlock-cn/reasonable-sorting#3]
游戏启动直接报崩溃，崩溃报告和游戏日志如下：
[crash-2021-11-03_15.10.01-server.txt](https://github.com/SolidBlock-cn/reasonable-sorting/files/7465900/crash-2021-11-03_15.10.01-server.txt
[latest.log](https://github.com/SolidBlock-cn/reasonable-sorting/files/7465903/latest.log)
)

**Comment by SolidBlock-cn** [comment]
好的，我会尽量解决此问题。1.15版本与后面的版本的Cloth Config都具有很大的区别，所以修复起来可能有点困难

**Comment by SolidBlock-cn** [comment]
经检查，本模组依赖的是Auto Config 1u的3.3.1版本，而非目前用于1.15.2的2.2.0。我会进行修改以兼容2.2.0版本。
在修复版发布之前，可以尝试将Auto Config 1u更新至3.3.1（尽管该版本推荐的版本不包括1.15.2）。

**Comment by SolidBlock-cn** [comment]
已发布新版本修复此问题。
