### ISSUE TITLE
Crashing in 1.18.2

### ISSUE THREAD

**Issue by Sqaaakoi** [SolidBlock-cn/reasonable-sorting#5]
Some registry related stuff is causing the game to crash for me in 1.18.2, here's the crash log: [crash-2022-03-05_18.40.46-client.txt](https://github.com/SolidBlock-cn/reasonable-sorting/files/8190066/crash-2022-03-05_18.40.46-client.txt)

This is probably due to item tags

**Comment by SolidBlock-cn** [comment]
OK I'll try to fix.

**Comment by SolidBlock-cn** [comment]
[reasonable-sorting-1.5-mc1.18.2.zip](https://github.com/SolidBlock-cn/reasonable-sorting/files/8190222/reasonable-sorting-1.5-mc1.18.2.zip)
Try this file (rename its file extension to `jar`). If that works normally, I'll publish it.

**Comment by KTibow** [comment]
The file you published works for me, and you can publish it.
