### ISSUE TITLE
[feature request] copy item when transfering or changing order

### ISSUE THREAD

**Issue by yesn0t** [SolidBlock-cn/reasonable-sorting#6]
Hello, using this mod is it possible to do (for example) :
* fence gates items in decoration and in redstone groups, at the same time.
* honey block in redstone group and honey block following honey bottle, at the same time.
* diamond block following dirt and diamond block following stone, at the same time.

I have read the [README](../blob/1.17//README-en.md) and i understand items can only be displayed in one place at a time, in the current version of the mod.

Ideally each sorting and transfer rule needs a copying equivalent or modifier. 

Please consider it, thanks x)

**Comment by SolidBlock-cn** [comment]
I'll try to improve this in the future.

Currently you can make an item in multiple groups using different multiple rules, for example, type `minecraft:slime_ball food` in custom transfer rule and type `minecraft:slime_ball tools` in custom regex transfer rule.

**Comment by yesn0t** [comment]
good to know, thank you !
