### ISSUE TITLE
1.18.1 Fabric - Crash with incompat between Reasonable Sorting, Applied Energetics 2 and Universal Graves

### ISSUE THREAD

**Issue by davidalb97** [SolidBlock-cn/reasonable-sorting#7]
**OS:** Linux (amd64) version 5.16.11-2-MANJARO
**DE:** KDE
**Java:** OpenJDK 17.0.3
**MC Version:** 1.18.1
**Mod loader:** Fabric

**Mod List: (Client)**
- ae2 10.1.0-beta.2
- cloth-config 6.2.57
- fabric 0.46.6+1.18
- fabricloader 0.13.3
- reasonable-sorting 1.5
- universal-graves 2.0.0-rc.5+1.18.1

**Mod List: (Server)**
- ae2 10.1.0-beta.2
- cloth-config 6.2.57
- fabric 0.46.6+1.18
- fabricloader 0.13.3
- universal-graves 2.0.0-rc.5+1.18.1

**Steps to reproduce:**
- Run a local server with the installed mods (excluding reasonable-sorting);
- Run minecraft client with all the mods;
- Join the server;
- In the server console, change gamemode from survival to creative;
- In the client, access the inventory, causing the game to crash.

**Expected behavior:** Can access the creative inventory without the game crashing, the inventory should be sorted with Reasonable Sorting mod. 

**Observed behavior:** Game crashes.

Minecraft log: https://pastebin.com/1kLK5qqn

**Note:** The crash does not occur when removing one of the required mods on the mod list.

**Issues on the other mod repositories:**
AppliedEnergistics/Applied-Energistics-2: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6101
Patbox/UniversalGraves: https://github.com/Patbox/UniversalGraves/issues/68

**Comment by SolidBlock-cn** [comment]
I looked through the crash report and did not find things related to this mod. If the issue still happens, you can reopen or reply.
