### ISSUE TITLE
Missing Extended Blockshape Sorting variant on GUI

### ISSUE THREAD

**Issue by ardissaps** [SolidBlock-cn/reasonable-sorting#9]
how can I make [ExtendedBlockshape ](https://www.curseforge.com/minecraft/mc-mods/extended-block-shapes)follow sort without typing them all one by one?

![image](https://user-images.githubusercontent.com/82106625/179764921-438bbc5b-e67e-4437-8567-a5e3cdee4728.png)

**Comment by SolidBlock-cn** [comment]
The Reasonable Sorting 2.0.0 does not support Extended Block Shapes 1.5.2 yet. Please downgrade to previous Reasonable Sorting version, or wait for the next Extended Block Shapes version. Sorry for the inconvenience.

**Comment by ardissaps** [comment]
> The Reasonable Sorting 2.0.0 does not support Extended Block Shapes 1.5.2 yet. Please downgrade to previous Reasonable Sorting version, or wait for the next Extended Block Shapes version. Sorry for the inconvenience.

The previous ReasonableSorting config sometimes does not work, like when loading world, the item not transfered.

**Comment by SolidBlock-cn** [comment]
Please try latest Reasonable Sorting and Extended Block Shapes mod.
